### ISSUE TITLE
Allow replacing portions of filearray by a single value

### ISSUE THREAD

**Issue by talegari** [dipterix/filearray#9]
Right now,

```r
library("filearray")
file = tempfile()
fa_obj = filearray_create(file, dimension = c(100, 1), type = "double")
fa_obj[1:10, 1] = 1
```

throws this error (not surprising):
```
Error in fa_subsetAssign1(x, i, ..., value = value) : 
  SubsetAssign FileArray `value` length mismatch.
```

Request: I have an usecase where large portions of filearray need to be replaced by a single value. It would be great to allow this exception. Else, I will have create large arrays in memory and then replace it.

**Comment by dipterix** [comment]
Thanks for this. Let me take a look at what I can do.

**Comment by dipterix** [comment]
The feature request has been implemented in the dev package. Will be included in the next CRAN release.
